---
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.102.3/hugo_0.102.3_Linux-64bit.deb
  - sudo dpkg -i hugo_0.102.3_Linux-64bit.deb

script:
  - hugo

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: master
